"""Add indexes and constraints

Revision ID: 8e3c7a9b2f1d
Revises: 2a84cf51810b
Create Date: 2026-04-04 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3c7a9b2f1d'
down_revision: Union[str, None] = '2a84cf51810b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add FK indexes for better join performance
    op.create_index('ix_bookings_house_id', 'bookings', ['house_id'])
    op.create_index('ix_bookings_tenant_id', 'bookings', ['tenant_id'])
    op.create_index('ix_houses_owner_id', 'houses', ['owner_id'])
    
    # Add CHECK constraints for data integrity
    op.create_check_constraint(
        'ck_houses_capacity_positive',
        'houses',
        sa.column('capacity') > 0
    )
    op.create_check_constraint(
        'ck_tariffs_amount_non_negative',
        'tariffs',
        sa.column('amount') >= 0
    )
    op.create_check_constraint(
        'ck_bookings_check_out_after_check_in',
        'bookings',
        sa.column('check_out') > sa.column('check_in')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop CHECK constraints
    op.drop_constraint('ck_bookings_check_out_after_check_in', 'bookings', type_='check')
    op.drop_constraint('ck_tariffs_amount_non_negative', 'tariffs', type_='check')
    op.drop_constraint('ck_houses_capacity_positive', 'houses', type_='check')
    
    # Drop indexes
    op.drop_index('ix_houses_owner_id', table_name='houses')
    op.drop_index('ix_bookings_tenant_id', table_name='bookings')
    op.drop_index('ix_bookings_house_id', table_name='bookings')
    
    # ### end Alembic commands ###
