"""Add consumable notes table

Revision ID: a1b2c3d4e5f6
Revises: 9f8e2c4d1a3b
Create Date: 2026-04-04 14:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '9f8e2c4d1a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create consumable_notes table
    op.create_table('consumable_notes',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('house_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_notes_id'), 'consumable_notes', ['id'], unique=False)
    op.create_index('ix_consumable_notes_house_id', 'consumable_notes', ['house_id'])
    op.create_index('ix_consumable_notes_created_by', 'consumable_notes', ['created_by'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop consumable_notes table
    op.drop_index('ix_consumable_notes_created_by', table_name='consumable_notes')
    op.drop_index('ix_consumable_notes_house_id', table_name='consumable_notes')
    op.drop_index(op.f('ix_consumable_notes_id'), table_name='consumable_notes')
    op.drop_table('consumable_notes')
    
    # ### end Alembic commands ###
